---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
data = read.csv("SN_m_tot_V2.0.csv", sep=";")
data
dates <- data[[3]]
monthly_means <- data[[4]]
plot(dates, monthly_means, type='s', col='blue', main='Sunspot Observations', xlab='Date', ylab='Monthly Mean Sunspots')
```

```{r}
# 5_number_summary
summary(monthly_means)
sd(monthly_means)
```

```{r}
# histogram
hist(monthly_means, xlab='Monthly Means', ylab='Number of Months', main='Distribution of Sunspot Data', breaks=8)
boxplot(monthly_means, main='Distribution of Sunspot Data', ylab='Monthly Means')
```

```{r}
points = c(0, 500, 1000, 1500, 2000, 2500, 3000, 3286)
for (k in 2:length(points)) {
  point_a = points[k-1]
  point_b = points[k]
  these_dates = dates[point_a:point_b]
  these_sunspots = monthly_means[point_a:point_b]
  plot(these_dates, these_sunspots, type='s', col='blue')
}
```

```{r}
##Analyzing Minima and Maxima CSV
data2 = read.csv("minima_maxima.csv", sep=",")
(cycle_nums<-data2[[1]])
length(cycle_nums)
periods<-data2[[4]]
maxima<-data2[[5]]
mean(periods)
sd(periods)
plot(cycle_nums, periods, type='p',col='blue', main='Periodicity', xlab='cycle', ylab='Period')
plot(cycle_nums, maxima, type='p', col='blue', main='Sunspot Maxima', xlab='cycle', ylab='sunspot number')
hist(periods, main='Distribution of Period Lengths', xlab='Period length')
summary(periods)
```

```{r}
# t-test
t.test(periods, alternative=c("two.sided"), mu=11)
```

